services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - donnees-h2:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  donnees-h2:
