-- V1 : schéma initial, identique au diagramme docs/diagrammes/D2-modele-donnees.md

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE etudiant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(100) NOT NULL,
    promotion_id BIGINT       NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE TABLE session_cours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(150) NOT NULL,
    promotion_id  BIGINT       NOT NULL,
    code          VARCHAR(6)   NOT NULL,
    ouverture_at  TIMESTAMP    NOT NULL,
    expiration_at TIMESTAMP    NOT NULL,
    cloturee_at   TIMESTAMP,
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id),
    CONSTRAINT uk_session_code UNIQUE (code)
);

-- RG5 : une présence par étudiant et par session ; RG6 : source ETUDIANT ou FORMATEUR
CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL,
    etudiant_id BIGINT      NOT NULL,
    source      VARCHAR(20) NOT NULL,
    marquee_at  TIMESTAMP   NOT NULL,
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))
);

-- RG12 : un exercice par étudiant et par session
CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL,
    etudiant_id BIGINT       NOT NULL,
    lien        VARCHAR(500) NOT NULL,
    statut      VARCHAR(30)  NOT NULL,
    depose_at   TIMESTAMP    NOT NULL,
    modifie_at  TIMESTAMP,
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU'))
);

-- RG8 : un seul relecteur par exercice ; RG3 : note entière de 0 à 20
CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT        NOT NULL,
    relecteur_id BIGINT        NOT NULL,
    note         INTEGER,
    commentaire  VARCHAR(2000),
    attribuee_at TIMESTAMP     NOT NULL,
    rendue_at    TIMESTAMP,
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id),
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR note BETWEEN 0 AND 20)
);
